# -*- coding: utf-8 -*-
"""dipt-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fh_vuKynC6mVdd3I_8Qmp9acRpX3EQDK
"""

import cv2
import matplotlib.pyplot as plt

img = cv2.imread('/content/happy (2).jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

_, global_thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
adaptive = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                 cv2.THRESH_BINARY, 11, 2)
_, otsu = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

titles = ['Original Image', 'Global Thresholding', 'Adaptive Thresholding', "Otsu's Method"]
images = [cv2.cvtColor(img, cv2.COLOR_BGR2RGB), global_thresh, adaptive, otsu]

plt.figure(figsize=(8, 6))
for i in range(4):
    plt.subplot(2, 2, i + 1)
    cmap = 'gray' if i > 0 else None
    plt.imshow(images[i], cmap=cmap)
    plt.title(titles[i])
    plt.axis('off')
plt.tight_layout()
plt.show()